# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('reference', models.TextField(blank=True, verbose_name='referencia')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='direccion')),
                ('techo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portada', verbose_name='Subir imagen')),
                ('maps', models.CharField(blank=True, max_length=500)),
                ('price', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('web', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Inscripcion de Cancha',
                'verbose_name_plural': 'Inscripcion de Cancha',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('asunto', models.CharField(max_length=300, verbose_name='asunto')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('email', models.EmailField(max_length=254)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Bandeja de mensajes',
            },
        ),
    ]
