# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscelanea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDeportivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('reference', models.TextField(blank=True, verbose_name='referencia')),
                ('addresse', models.CharField(blank=True, max_length=100, verbose_name='direccion')),
                ('techo', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portada', verbose_name='Subir imagen')),
                ('maps', models.CharField(blank=True, max_length=500)),
                ('phone', models.ManyToManyField(blank=True, to='miscelanea.Phone', verbose_name='telefonos')),
                ('price', models.ManyToManyField(blank=True, to='miscelanea.Price', verbose_name='precios')),
                ('tag', models.ManyToManyField(blank=True, to='miscelanea.Tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Campo Deportivo',
                'verbose_name_plural': 'Campos Deportivos',
            },
        ),
    ]
