# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campodeportivo',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
