# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0002_campodeportivo_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='campodeportivo',
            name='slug',
            field=models.SlugField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
